spring:
  datasource:
    url: jdbc:h2:mem:auth_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: vRTyyMFjreT5m8KHfHADf8twbs9iNgL1d67BtGGtYlu